version: "3.8"

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    extra_hosts:
      - "host.docker.internal:host-gateway"
    healthcheck:
      test: ["CMD", "wget", "--spider", "http://localhost:5678/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
 
  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 10s
      timeout: 5s
      retries: 5

  supabase-studio:
    image: supabase/studio:latest
    ports:
      - "3000:3000"
    environment:
      STUDIO_PG_META_URL: http://meta:8081
      POSTGRES_PASSWORD: n8n
    depends_on:
      postgres:
        condition: service_healthy

  rest:
    image: postgrest/postgrest:v10.1.2
    environment:
      PGRST_DB_URI: postgres://n8n:n8n@postgres:5432/n8n
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
    depends_on:
      postgres:
        condition: service_healthy

  meta:
    image: supabase/postgres-meta:v0.68.0
    ports:
      - "8081:8081"
    environment:
      PG_META_PORT: 8081
      PG_META_DB_HOST: postgres
      PG_META_DB_PASSWORD: n8n
      PG_META_DB_USER: n8n
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  n8n_data:
  postgres_data: