version: "3.8"

services:
  traefik:
    image: traefik:v2.5
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.tlschallenge=true"
      - "--certificatesresolvers.myresolver.acme.email=tu@email.com"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./letsencrypt:/letsencrypt"
    networks:
      - n8n-network

  n8n:
    image: n8nio/n8n
    environment:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_DATABASE=n8n
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_USER=n8n
      - DB_POSTGRESDB_PASSWORD=n8n
      - N8N_HOST=alamo.yalovio.com
      - N8N_PROTOCOL=https
      - NODE_ENV=production
      - WEBHOOK_URL=https://alamo.yalovio.com/
      - N8N_EDITOR_BASE_URL=https://alamo.yalovio.com
      - GENERIC_TIMEZONE=America/New_York
    volumes:
      - n8n_data:/home/node/.n8n
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - n8n-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.n8n.rule=Host(`alamo.yalovio.com`)"
      - "traefik.http.routers.n8n.entrypoints=websecure"
      - "traefik.http.routers.n8n.tls.certresolver=myresolver"
      - "traefik.http.services.n8n.loadbalancer.server.port=5678"

  postgres:
    image: postgres:13
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U n8n"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - n8n-network

  tigase:
    image: "wojciechkapciatig/tests:nightly"
    restart: unless-stopped
    hostname: redloop.yalovio.com
    depends_on:
      tigase-db:
        condition: service_healthy
    ports:
      - "8080:8080"
      - "5222:5222"
      - "5223:5223"
      - "5269:5269"
      - "5280:5280"
      - "5281:5281"
      - "5290:5290"
      - "5291:5291"
    volumes:
      - ./tigase-server/etc:/home/tigase/tigase-server/etc
      - ./tigase-server/data:/home/tigase/tigase-server/data
      - ./tigase-server/logs:/home/tigase/tigase-server/logs
      - ./tigase-server/certs:/home/tigase/tigase-server/certs
      - ./tigase-server/tigasedb:/home/tigase/tigase-server/tigasedb
    environment:
      - PRODUCTION_HEAP_SETTINGS
      - DB_TYPE=postgresql
      - DB_HOST=tigase-db
      - DB_PORT=5432
      - DB_ROOT_USER=postgres
      - DB_ROOT_PASS=root
      - DEFAULT_VIRTUAL_DOMAIN=redloop.yalovio.com
    networks:
      - n8n-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 10s
      retries: 5
    privileged: true
    sysctls:
      net.core.somaxconn: 1024
      net.ipv4.tcp_syncookies: 0
      net.ipv4.tcp_keepalive_time: 60
      net.ipv4.tcp_keepalive_probes: 3
      net.ipv4.tcp_keepalive_intvl: 90
      net.ipv4.tcp_retries2: 4
    ulimits:
      nofile:
        soft: 350000
        hard: 350000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.tigase.rule=Host(`redloop.yalovio.com`)"
      - "traefik.http.routers.tigase.entrypoints=websecure"
      - "traefik.http.routers.tigase.tls.certresolver=myresolver"
      - "traefik.http.services.tigase.loadbalancer.server.port=8080"

  tigase-db:
    image: postgres:14
    restart: unless-stopped
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - ./tigase-db/data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 30
    networks:
      - n8n-network

  coturn:
    image: coturn/coturn
    restart: unless-stopped
    ports:
      - "3478:3478"
      - "3478:3478/udp"
      - "5349:5349"
      - "5349:5349/udp"
      - "8099:8099"
      - "49160-49200:49160-49200"
    command:
      - -n
      - --log-file=stdout
      - --min-port=49160
      - --max-port=49200
      - --realm=redloop.yalovio.com
      - --user=tigase:tigase
      - --lt-cred-mech
      - --fingerprint
      - --external-ip=$(detect-external-ip)
    volumes:
      - ./coturn/coturn/turnserver.conf:/etc/coturn/turnserver.conf:ro
      - ./coturn/.cache/data:/var/lib/coturn
    networks:
      - n8n-network

networks:
  n8n-network:
    driver: bridge

volumes:
  n8n_data:
  postgres_data:
  letsencrypt: