-- Crear extensión vector
CREATE EXTENSION IF NOT EXISTS vector;

-- Asignar permisos al usuario n8n
GRANT ALL PRIVILEGES ON SCHEMA public TO n8n;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO n8n;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO n8n;

-- Asegurar que los nuevos objetos también tengan los permisos correctos
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON TABLES TO n8n;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL PRIVILEGES ON SEQUENCES TO n8n;