version: '3'
services:
  prosody:
    build: .
    container_name: prosody-server
    ports:
      - "5222:5222"
      - "5269:5269"
    volumes:
      - ./prosody.cfg.lua:/etc/prosody/prosody.cfg.lua
      - ./certs:/etc/prosody/certs
    restart: unless-stopped
